config/routes.rb
Rails.application.routes.draw do
  
  # Set Views/Home/index is the main page
  root 'home#index'
  get 'home/index', to: 'home#index'
  
  get 'home/about'
  get 'home/contact'
  get 'home/faq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
  def contact
  end
  def faq
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<!--======= INTRO SECTION  -->

 <section class="inner-intro bg-6 ">
  <div class="container">
     <div class="row text-center intro-title">
           <div class="col-lg-6 col-md-6 col-sm-6 text-left">
             <h1 class="text-white">About us </h1>
           </div>
           <div class="col-lg-6 col-md-6 col-sm-6 text-right">
             <ul class="page-breadcrumb">
                <li><a href="#"><i class="fa fa-home"></i> Home</a> <i class="fa fa-angle-double-right"></i></li>
                <li><a href="#">pages</a> <i class="fa fa-angle-double-right"></i></li>
                <li><span>About Us</span> </li>
             </ul>
        </div>
     </div>
  </div>
</section>
<!--======= INTRO SECTION  -->

<!--======= WELCOME SECTION  -->

<section class="welcome-4 page-section-ptb white-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-1 col-md-10">
         <div class="section-title">
           <span>Welcome to </span>
           <h2>the Cardealer online</h2>
           <div class="separator"></div>
           <p>Car Dealer is the Free Ruby On Rails Template . We provide everything you need to build an <strong>Amazing dealership website</strong>  developed especially for car sellers, dealers or auto motor retailers. You can use this template for creating website based on any framework language.</p>
         </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="owl-carousel-5">
         <div class="item">
           <%= image_tag ('car/a1.png'), :class => "img-responsive objects-1", :alt =>"" %>

          </div>
          <div class="item">
            <%= image_tag ('car/a2.png'), :class => "img-responsive objects-1", :alt =>"" %>

          </div>
          <div class="item">
            <%= image_tag ('car/a3.png'), :class => "img-responsive objects-1", :alt =>"" %>

          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6">
        <p>Dealer obcaecati adipisci vero lorem ipsum dolor sit amet, consectetur adipisicing elit. dolorum pariatur aut consectetur. Sit quisquam rerum corporis neque atque inventore nulla, quibusdam, ipsa suscipit aperiam reiciendis, ea odio?</p>
        <br />
        <p>Adipisicing ipsum dolor sit amet, consectetur elit. Obcaecati adipisci vero dolorum pariatur aut consectetur. Sit quisquam rerum corporis neque atque inventore nulla, quibusdam, ipsa suscipit aperiam reiciendis, ea odio?</p>
        <p>Obcaecati adipisci vero dolorum pariatur aut consectetur. lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit quisquam rerum corporis neque atque inventore nulla, quibusdam, ipsa suscipit aperiam reiciendis, ea odio?</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-car"></i>
          </div>
          <div class="content">
            <h6>All brands </h6>
            <p>Obcaecati adipisci vero dolorum pariatur </p>
          </div>
         </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-comments-o"></i>
          </div>
          <div class="content">
            <h6>Free Support</h6>
            <p>lorem ipsum dolor sit amet, consectetur</p>
          </div>
         </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-key"></i>
          </div>
          <div class="content">
            <h6>Dealership </h6>
            <p>Sit quisquam rerum corporis neque</p>
          </div>
         </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-address-card"></i>
          </div>
          <div class="content">
            <h6>affordable</h6>
            <p>Suscipit aperiam reiciendis, ea odio?</p>
          </div>
         </div>
      </div>
    </div>
  </div>
</section>

<!--======= WELCOME SECTION  -->

<hr class="gray" />

<!--======= HISTORY SECTION  -->

<section class="our-history gray-bg page-section-ptb">
  <div class="container">
   <div class="row">
    <div class="col-lg-12 col-md-12">
      <div class="section-title">
         <span>Car dealer's 30 year timeline from the beginning</span>
         <h2>our history</h2>
         <div class="separator"></div>
      </div>
    </div>
   </div>
   <div class="row">
    <div class="col-lg-12 col-md-12">
       <ul class="timeline list-style-none">
        <li>
          <div class="timeline-badge"><h4>01</h4></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h5>the beginning</h5>
            </div>
            <div class="timeline-body">
              <p>From the beginning lorem ipsum dolor sit amet, consectetur sed do eiusmod tempor incididunt ut labore.</p>
            </div>
          </div>
        </li>
        <li class="timeline-inverted">
          <div class="timeline-badge"><h4>02</h4></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h5>New Service Garage</h5>
            </div>
            <div class="timeline-body">
              <p>We own our own New Service Garage incididunt Lorem ipsum dolor sit amet consectetur adipiscing elit.</p>
            </div>
          </div>
        </li>
        <li>
          <div class="timeline-badge"><h4>03</h4></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h5>New Main office</h5>
            </div>
            <div class="timeline-body">
              <p>With new super cool office elit lorem ipsum dolor sit amet sed do eiusmod tempor incididunt ut labore.</p>
            </div>
          </div>
        </li>

        <li class="timeline-inverted">
          <div class="timeline-badge"><h4>04</h4></div>
          <div class="timeline-panel">
            <div class="timeline-heading">
              <h5>New Website launch</h5>
            </div>
            <div class="timeline-body">
              <p>Start online business tempor lorem ipsum dolor sit amet, consectetur adipiscing elit incididunt ut labore.</p>
            </div>
          </div>
        </li>
     </ul>
    </div>
   </div>
  </div>
</section>
<!--======= HISTORY SECTION  -->

<!--======= COUNTER SECTION  -->

<section class="counter counter-style-2 bg-red bg-1 bg-overlay-black-70 page-section-ptb">
  <div class="container">
    <div class="row">
     <div class="col-lg-3 col-md-3 col-sm-6 item">
     <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Vehicles in Stock</h6>
           <p><i class="fa fa-car"></i>
           <h3 class="text-white">550</h3></p>
         </div>
        </div>
     </div>
     <div class="col-lg-3 col-md-3 col-sm-6 item">
     <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Dealer Reviews</h6>
           <p>  <i class="fa fa-comments-o"></i></i>
           <h3 class="text-white">2500</h3></p>
         </div>
        </div>
     </div>
     <div class="col-lg-3 col-md-3 col-sm-6 item">
     <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Happy Customer</h6>
           <p><i class="fa fa-users"></i>
           <h3 class="text-white">10050</h3></p>
         </div>
        </div>
     </div>
      <div class="col-lg-3 col-md-3 col-sm-6 item">
      <div class="counter-block text-left">
        <div class="separator"></div>
        <div class="info">
           <h6 class="text-white">Awards</h6>
           <p><i class="fa fa-trophy"></i>
           <h3 class="text-white">350</h3></p>
         </div>
        </div>
     </div>
    </div>
  </div>
</section>

<!--======= COUNTER SECTION  -->

<!--======= TESTMONIAL SECTION  -->

 <section class="testimonial-1 gray-new-bg  page page-section-ptb">
   <div class="container">
     <div class="row">
       <div class="col-lg-12 col-md-12">
         <div class="section-title">
           <span>What Our Happy Clients say about us</span>
           <h2>our Testimonial
           </h2>
           <div class="separator"></div>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="col-lg-12 col-md-12">
         <div class="owl-carousel-2">
           <div class="item">
             <div class="testimonial-block text-center border-new">
               <div class="testimonial-image">

                 <%= image_tag('testimonial/01.jpg', :alt => "", :class => "img-responsive") %>

               </div>
               <div class="testimonial-box">
                 <div class="testimonial-avtar">
                   <%= image_tag('team/01.jpg', :alt => "", :class => "img-responsive") %>

                   <h6>Alice Williams</h6>
                   <span>Auto Dealer</span>
                 </div>
                 <div class="testimonial-content">
                   <p>It has survived not only five centuries. lorem Ipsum is simply dummy text of the printin a galley of type and bled it to make a type specimen book.</p>
                   <i class="fa fa-quote-right"></i>
                 </div>
               </div>
             </div>
           </div>
           <div class="item">
             <div class="testimonial-block text-center border-new" >
               <div class="testimonial-image">

                 <%= image_tag('testimonial/02.jpg', :alt => "", :class => "img-responsive") %>

               </div>
               <div class="testimonial-box" >
                 <div class="testimonial-avtar">
                   <%= image_tag('team/02.jpg', :alt => "", :class => "img-responsive") %>

                   <h6>Michael Bean</h6>
                   <span>Car Dealer</span>
                 </div>
                 <div class="testimonial-content">
                   <p>A galley of type and bled it to make a type specimen book. Ipsum is simply dummy text of the printin It has survived not only five centuries.</p>
                   <i class="fa fa-quote-right"></i>
                 </div>
               </div>
             </div>
           </div>
           <div class="item">
             <div class="testimonial-block text-center border-new">
               <div class="testimonial-image">

                 <%= image_tag('testimonial/03.jpg', :alt => "", :class => "img-responsive") %>

               </div>
               <div class="testimonial-box">
                 <div class="testimonial-avtar">
                   <%= image_tag('team/03.jpg', :alt => "", :class => "img-responsive") %>

                   <h6>Felica Queen</h6>
                   <span>Auto Dealer</span>
                 </div>
                 <div class="testimonial-content">
                   <p>Text of the printin a galley of type and bled it to a type specimen book. It has survived not only five centuries make Lorem Ipsum is simply dummy.</p>
                   <i class="fa fa-quote-right"></i>
                 </div>
               </div>
             </div>
           </div>
           <div class="item">
             <div class="testimonial-block text-center border-new">
               <div class="testimonial-image">

                 <%= image_tag('testimonial/04.jpg', :alt => "", :class => "img-responsive") %>

               </div>
               <div class="testimonial-box">
                 <div class="testimonial-avtar">
                   <%= image_tag('team/04.jpg', :alt => "", :class => "img-responsive") %>

                   <h6>Sara Lisbon</h6>
                   <span>Customer</span>
                 </div>
                 <div class="testimonial-content">
                   <p>Printin a galley of type and bled It has survived not lorem Ipsum is simply dummy text of the it to make a type specimen book only five centuries.</p>
                   <i class="fa fa-quote-right"></i>
                 </div>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
   </div>
 </section>
<!--======= COUNTER SECTION  -->

app/views/home/contact.html.erb
<!--======= INTRO  SECTION  -->

<section class="inner-intro bg-1 bg-overlay-black-70">
  <div class="container">
    <div class="row text-center intro-title">
      <div class="col-lg-6 col-md-6 col-sm-6 text-left">
        <h1 class="text-white">Conatct us </h1>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 text-right">
        <ul class="page-breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i> Home</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <a href="#">pages</a>
            <i class="fa fa-angle-double-right"></i>
          </li>
          <li>
            <span>Conatct Us</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!--======= INTRO  SECTION  -->

<!--======= CONTACT SECTION  -->

<section class="contact page-section-ptb gray-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="section-title">
          <span>We’d Love to Hear From You</span>
          <h2>LET'S GET IN TOUCH!</h2>
          <div class="separator"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-map-marker"></i>
          <h5>Address</h5>
          <p>220E Front St. Burlington NC 215</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-phone"></i>
          <h5>Phone</h5>
          <p> (007) 123 456 7890</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-envelope-o"></i>
          <h5>Email</h5>
          <p> support@website.com</p>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="contact-box text-center">
          <i class="fa fa-fax"></i>
          <h5>Fax</h5>
          <p>(007) 123 456 7890</p>
        </div>
      </div>
    </div>
    <div class="page-section-ptb">
      <div class="row">
        <div class="col-lg-8 col-md-8">
          <div class="gray-form row">
            <div id="formmessage">Success/Error Message Goes Here</div>
            <form class="form-horizontal" id="contactform" role="form" method="post" action="php/contact-form.php">
              <div class="contact-form">
                <div class="col-lg-4 col-md-4">
                  <div class="form-group">
                    <input id="name" type="text" placeholder="Name*" class="form-control" name="name">
                  </div>
                </div>
                <div class="col-lg-4 col-md-4">
                  <div class="form-group">
                    <input type="email" placeholder="Email*" class="form-control" name="email">
                  </div>
                </div>
                <div class="col-lg-4 col-md-4">
                  <div class="form-group">
                    <input type="text" placeholder="Phone*" class="form-control" name="phone">
                  </div>
                </div>
                <div class="col-lg-12 col-md-12">
                  <div class="form-group">
                    <textarea class="form-control input-message" placeholder="Comment*" rows="7" name="message"></textarea>
                  </div>
                </div>
                <div class="col-lg-4 col-md-4 col-md-offset-4">
                  <input type="hidden" name="action" value="sendEmail" />
                  <button id="submit" name="submit" type="submit" value="Send" class="button red"> Send your message </button>
                </div>
              </div>
            </form>
            <div id="ajaxloader" style="display:none">
              <img class="center-block" src="images/ajax-loader.gif" alt="">
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-4">
          <div class="opening-hours gray-bg">
            <h6>opening hours</h6>
            <ul class="list-style-none">
              <li>
                <strong>Sunday</strong>
                <span class="text-red"> closed</span>
              </li>
              <li>
                <strong>Monday</strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Tuesday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Wednesday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Thursday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Friday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
              <li>
                <strong>Saturday </strong>
                <span> 9:00 AM to 9:00 PM</span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-clock-o"></i>
          </div>
          <div class="content">
            <h6>opening hours </h6>
            <p>Voluptatem accusanoremque sed ut perspiciatis unde omnis iste natus error sit laudantium, totam rem aperiam.
              </p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-support"></i>
          </div>
          <div class="content">
            <h6>Our Support Center </h6>
            <p>Iste natus error sit sed ut perspiciatis unde omnis voluptatem laudantium, totam rem aperiam. </p>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4">
        <div class="feature-box-3">
          <div class="icon">
            <i class="fa fa-info"></i>
          </div>
          <div class="content">
            <h6>Some Information </h6>
            <p>Totam rem aperiam sed ut perspiciatis unde omnis iste natus error sit voluptatem laudantium.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!--======= CONTACT SECTION  -->


<!--======= CONTACT MAP SECTION  -->

<section class="contact-map">
  <div class="container-fluid">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3224.017231421863!2d-79.43780268425046!3d36.09306798010035!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88532bae09664ccb%3A0xaa6b8f98d3fb8135!2s220+E+Front+St%2C+Burlington%2C+NC+27215%2C+USA!5e0!3m2!1sen!2sin!4v1475045272926"
      allowfullscreen></iframe>
  </div>
</section>

<!--======= CONTACT MAP SECTION  -->

app/views/layouts/_footer.html.erb
<!--=======FOOTER  -->

<footer class="footer bg-2 bg-overlay-black-90">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="social">
          <ul>
            <li>
              <a class="facebook" href="#">facebook
                <i class="fa fa-facebook"></i>
              </a>
            </li>
            <li>
              <a class="twitter" href="#">twitter
                <i class="fa fa-twitter"></i>
              </a>
            </li>
            <li>
              <a class="pinterest" href="#">pinterest
                <i class="fa fa-pinterest-p"></i>
              </a>
            </li>
            <li>
              <a class="dribbble" href="#">dribbble
                <i class="fa fa-dribbble"></i>
              </a>
            </li>
            <li>
              <a class="google-plus" href="#">google plus
                <i class="fa fa-google-plus"></i>
              </a>
            </li>
            <li>
              <a class="behance" href="#">behance
                <i class="fa fa-behance"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="about-content">
          <a href="#">
            <%= image_tag('logo-light.png', :alt => "logo", :class => "img-responsive") %></a>
            <p>We provide everything you need to build an amazing dealership website developed especially for car sellers dealers or auto motor retailers.</p>
        </div>
        <div class="address">
          <ul>
            <li>
              <i class="fa fa-map-marker"></i>
              <span>220E Front St. Burlington NC 27215</span>
            </li>
            <li>
              <i class="fa fa-phone"></i>
              <span>(007) 123 456 7890</span>
            </li>
            <li>
              <i class="fa fa-envelope-o"></i>
              <span>support@website.com</span>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="usefull-link">
          <h6 class="text-white">Useful Links</h6>
          <ul>
            <li>
              <a href="#">
                <i class="fa fa-angle-double-right"></i>
                Change Oil and Filter</a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-angle-double-right"></i>
                Brake Pads Replacement</a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-angle-double-right"></i>
                Timing Belt Replacement</a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-angle-double-right"></i>
                Pre-purchase Car Inspection</a>
            </li>
            <li>
              <a href="#">
                <i class="fa fa-angle-double-right"></i>
                Starter Replacement</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="recent-post-block">
          <h6 class="text-white">recent posts
          </h6>
          <div class="recent-post">
            <div class="recent-post-image">
              <%= image_tag('car/01.jpg', :alt => "", :class => "img-responsive") %>

            </div>
            <div class="recent-post-info">
              <a href="#">Time to change your
              </a>
              <span class="post-date">
                <i class="fa fa-calendar"></i>JAN 10, 2018</span>
            </div>
          </div>
          <div class="recent-post">
            <div class="recent-post-image">
              <%= image_tag('car/02.jpg', :alt => "", :class => "img-responsive") %>

            </div>
            <div class="recent-post-info">
              <a href="#">The best time to
              </a>
              <span class="post-date">
                <i class="fa fa-calendar"></i>JAN 10, 2018</span>
            </div>
          </div>
          <div class="recent-post">
            <div class="recent-post-image">
              <%= image_tag('car/03.jpg', :alt => "", :class => "img-responsive") %>

            </div>
            <div class="recent-post-info">
              <a href="#">Replacing a timing
              </a>
              <span class="post-date">
                <i class="fa fa-calendar"></i>JAN 10, 2018</span>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-6">
        <div class="news-letter">
          <h6 class="text-white">subscribe Our Newsletter
          </h6>
          <p>Keep up on our always evolving products features and technology. Enter your e-mail and subscribe to our newsletter.</p>
          <form class="news-letter">
            <input type="email" placeholder="Enter your Email" class="form-control placeholder">
            <a class="button red" href="#">Subscribe</a>
          </form>
        </div>
      </div>
    </div>
    <hr/>
    <div class="copyright">
      <div class="row">
        <div class="col-lg-6 col-md-6">
          <div class="text-left">
            <p>©Copyright 2018 Concept Car Dealer Developed by
              <a href="http://www.devdap.com/" target="_blank">devdap.com</a>
            </p>
          </div>
        </div>
        <div class="col-lg-6 col-md-6">
          <ul class="list-inline text-right">
            <li>
              <a href="#">privacy policy
              </a>
              |
            </li>
            <li>
              <a href="#">terms and conditions
              </a>
              |</li>
            <li>
              <a href="#">contact us
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<!--=======FOOTER  -->

<!--=======BACK TO TOP  -->

<div class="car-top">
  <span><%= image_tag('car.png', :alt => "") %></span>
</div>

<!--=======BACK TO TOP  -->

app/views/layouts/_navigation.html.erb
<!--================================= Loading -->
<div id="loading">
  <div id="loading-center">
    <%= image_tag('loader.gif', :alt => "") %>
  </div>
</div>
<!--================================= Loading -->

<!--================================= Header  -->
<header id="header" class="defualt">
  <div class="menu">
    <nav id="menu" class="mega-menu">
      <section class="menu-list-items">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 col-md-12">
              <ul class="menu-logo">
                <li>
                  <%= link_to root_path do %>
                  <%= image_tag "logo-light.png", class: "" %><% end %>
                </li>
              </ul>
              <ul class="menu-links">
                <li class="active">
                  <%= link_to 'Home', home_index_path %>
                </li>
                <li>
                  <%= link_to 'About Us', home_about_path %>
                </li>
                <li>
                  <%= link_to 'FAQ', home_faq_path %>
                </li>
                <li>
                  <%= link_to 'Contact Us', home_contact_path %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>
    </nav>
  </div>
</header>
<!--================================= Header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="keywords" content="Free Ruby On Rails 5 Template" />
<meta name="description" content="Concept Car Dealer - Free Ruby On Rails 5 Template" />
<meta name="author" content="devdap.com" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

    

    <!-- Title -->
    <title>Concept Car Dealer - Free Ruby On Rails 5 Template</title>

    <!-- Favicon -->
    <%= favicon_link_tag 'favicon.ico' %>
    
    <!-- Stylesheets -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Menu Partials -->
    <%= render 'layouts/navigation' %>
    
     <%= yield %>
    
    <!-- Footer Partials -->
    <%= render 'layouts/footer' %>

    <!-- Javascripts -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>